export default {
  'Category Management': 'Danh mục',
  'Order Management': 'Đơn hàng',
  'Product Management': 'Hàng hóa',
  'Production Management': 'Sản xuất',
  'Quota Management': 'Định mức',
  'Role Management': 'Vai trò và quyền',
  Setting: 'Cấu hình cài đặt',
  'Stage Management': 'Quy trình - công đoạn',
  'User Management': 'Người dùng',
  'Warehouse Management': 'Kho',
  Report: 'Báo cáo',
  Factory: 'Xưởng sản xuất',

  'View Category': 'Xem danh sách danh mục',
  'Create Category': 'Tạo danh mục',
  'Edit Category': 'Chỉnh sửa danh mục',
  'Delete Category': 'Xóa danh mục',

  'View Customer': 'Xem danh sách khách hàng',
  'Create Customer': 'Tạo khách hàng',
  'Edit Customer': 'Chỉnh sửa khách hàng',
  'Delete Customer': 'Xóa khách hàng',
  'View Provider': 'Xem danh sách nhà cung cấp',
  'Create Provider': 'Tạo nhà cung cấp',
  'Edit Provider': 'Chỉnh sửa nhà cung cấp',
  'Delete Provider': 'Xóa nhà cung cấp',
  'View Order': 'Xem danh sách đơn đặt hàng',
  'Create Order': 'Chỉnh sửa đơn đặt hàng',
  'Edit Order': 'Chỉnh sửa đơn đặt hàng',
  'Delete Order': 'Xóa đơn đặt hàng',
  'View Order History': 'Xem lịch sử đơn đặt hàng',

  'View Product': 'Xem danh sách thành phẩm',
  'Create Product': 'Tạo thành phẩm',
  'Edit Product': 'Chỉnh sửa thành phẩm',
  'Delete Product': 'Xóa thành phẩm',
  'View Semi Product': 'Xem danh sách bán thành phẩm',
  'Create Semi Product': 'Tạo bán thành phẩm',
  'Edit Semi Product': 'Chỉnh sửa bán thành phẩm',
  'Delete Semi Product': 'Xóa bán thành phẩm',
  'View Material': 'Xem danh sách nguyên vật liệu',
  'Create Material': 'Tạo nguyên vật liệu',
  'Edit Material': 'Chỉnh sửa nguyên vật liệu',
  'Delete Material': 'Xóa nguyên vật liệu',

  'View Request Export Material Ticket': 'Xem danh sách đề nghị xuất vật tư',
  'Create Request Export Material Ticket': 'Tạo đề nghị xuất vật tư',
  'Edit Request Export Material Ticket': 'Chỉnh sửa đề nghị xuất vật tư',
  'Delete Request Export Material Ticket': 'Xóa đề nghị xuất vật tư',
  'View Production Progress': 'Xem tiến độ sản xuất',
  'Update Production Progress': 'Cập nhật tiến độ sản xuất',
  'Update Production Progress Directly': 'Cập nhật tiến độ sản xuất trực tiếp',
  'View Machining Progress': 'Xem tiến độ gia công',
  'Update Machining Progress': 'Chỉnh sửa tiến độ gia công',
  'View Export Machining Ticket': 'Xem danh sách xuất gia công',
  'Create Export Machining Ticket': 'Tạo xuất gia công',
  'Edit Export Machining Ticket': 'Chỉnh sửa xuất gia công',
  'Delete Export Machining Ticket': 'Xóa xuất gia công',
  'View Import Machining Ticket': 'Xem danh sách nhập gia công',
  'Create Import Machining Ticket': 'Tạo nhập gia công',
  'Edit Import Machining Ticket': 'Chỉnh sửa nhập gia công',
  'Delete Import Machining Ticket': 'Xóa nhập gia công',
  'View Production Order': 'Xem danh sách lệnh sản xuất',
  'Create Production Order': 'Tạo lệnh sản xuất',
  'Edit Production Order': 'Chỉnh sửa lệnh sản xuất',
  'Delete Production Order': 'Xóa lệnh sản xuất',
  'Approve Production Order': 'Duyệt lệnh sản xuất',
  'Production Order View Material List': 'Xem danh sách vật tư trong lệnh sản xuất',
  'Production Order Delete Material': 'Xóa vật tư trong lệnh sản xuất',
  'Production Order Edit Material': 'Chỉnh sửa vật tư trong lệnh sản xuất',
  'Production Order Add Material': 'Tạo vật tư trong lệnh sản xuất',
  'Production Order Delete Product': 'Xóa thành phẩm trong lệnh sản xuất',
  'Production Order Edit Product': 'Chỉnh sửa thành phẩm trong lệnh sản xuất',
  'Production Order Add Product': 'Tạo thành phẩm trong lệnh sản xuất',
  'Production Order View Product List': 'Xem danh sách thành phẩm trong lệnh sản xuất',
  'Purchase Production Order': 'Thanh toán lệnh sản xuất',
  'Technical Inspection Production Order': 'Kiểm duyệt kỹ thuật lệnh sản xuất',
  'Producing Production Order': 'Tiến hành lệnh sản xuất',
  'Promulgate Production Order': 'Ban hành lệnh sản xuất',

  'View Product Quota': 'Xem danh sách định mức thành phẩm',
  'Create Product Quota': 'Tạo định mức thành phẩm',
  'Edit Product Quota': 'Chỉnh sửa định mức thành phẩm',
  'Delete Product Quota': 'Xóa định mức thành phẩm',
  'View Semi Product Quota': 'Xem danh sách định mức bán thành phẩm',
  'Create Semi Product Quota': 'Tạo định mức thành phẩm',
  'Edit Semi Product Quota': 'Chỉnh sửa định mức thành phẩm',
  'Delete Semi Product Quota': 'Xóa định mức thành phẩm',
  'View Raw Product Quota': 'Xem danh sách định mức phôi',
  'Create Raw Product Quota': 'Tạo định mức phôi',
  'Edit Raw Product Quota': 'Chỉnh sửa định mức phôi',
  'Delete Raw Product Quota': 'Xóa định mức phôi',

  'View Role': 'Xem danh sách quyền',
  'Create Role': 'Tạo quyền',
  'Edit Role': 'Chỉnh sửa quyền',
  'Delete Role': 'Xóa quyền',

  'View General Setting': 'Xem cấu hình cài đặt',
  'Update General Setting': 'Cập nhật cấu hình cài đặt',

  'View Stage Group': 'Xem danh sách quy trình',
  'Create Stage Group': 'Tạo quy trình',
  'Edit Stage Group': 'Chỉnh sửa quy trình',
  'Delete Stage Group': 'Xóa quy trình',
  'View Stage': 'Xem danh sách công đoạn',
  'Create Stage': 'Tạo công đoạn',
  'Edit Stage': 'Chỉnh sửa công đoạn',
  'Delete Stage': 'Xóa công đoạn',

  'View User': 'Xem danh sách người dùng',
  'Create User': 'Tạo người dùng',
  'Edit User': 'Chỉnh người dùng',
  'Delete User': 'Xóa người dùng',

  'View Import Warehouse Ticket': 'Xem danh sách phiếu nhập kho',
  'Create Import Warehouse Ticket': 'Tạo phiếu nhập kho',
  'Edit Import Warehouse Ticket': 'Chỉnh sửa phiếu nhập kho',
  'Delete Import Warehouse Ticket': 'Xóa phiếu nhập kho',
  'View Warehouse': 'Xem danh sách kho',
  'Create Warehouse': 'Tạo kho',
  'Edit Warehouse': 'Chỉnh sửa kho',
  'Delete Warehouse': 'Xóa kho',
  'View Export Warehouse Ticket': 'Xem danh sách phiếu xuất kho',
  'Create Export Warehouse Ticket': 'Tạo phiếu xuất kho',
  'Edit Export Warehouse Ticket': 'Chỉnh sửa phiếu xuất kho',
  'Delete Export Warehouse Ticket': 'Xóa phiếu xuất kho',
  'View Request Export Warehouse Ticket': 'Xem danh sách đề nghị xuất kho',
  'Create Request Export Warehouse Ticket': 'Tạo đề nghị xuất kho',
  'Edit Request Export Warehouse Ticket': 'Chỉnh sửa đề nghị xuất kho',
  'Delete Request Export Warehouse Ticket': 'Xóa đề nghị xuất kho',

  'View Production Progress Report': 'Báo cáo tiến độ sản xuất',

  'View Factory': 'Xem danh sách xưởng sản xuất',
  'Create Factory': 'Tạo xưởng sản xuất',
  'Edit Factory': 'Chỉnh sửa xưởng sản xuất',
  'Delete Factory': 'Xóa xưởng sản xuất',
};
